//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tli_Utils {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tli_Utils.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Activation Medium Skill과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcActivationMediumSkill {
            get {
                return ResourceManager.GetString("calcActivationMediumSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcCool {
            get {
                return ResourceManager.GetString("calcCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcFreeze {
            get {
                return ResourceManager.GetString("calcFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order/Chaos Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcNewGod {
            get {
                return ResourceManager.GetString("calcNewGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frostfire Rampage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FrostRampage {
            get {
                return ResourceManager.GetString("FrostRampage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightning Shadow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lightning_Shadow {
            get {
                return ResourceManager.GetString("Lightning Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chzzk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strCzz {
            get {
                return ResourceManager.GetString("strCzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Github과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strGithub {
            get {
                return ResourceManager.GetString("strGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go Main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strGoMain {
            get {
                return ResourceManager.GetString("strGoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Youtube과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strYoutube {
            get {
                return ResourceManager.GetString("strYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guides과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_0 {
            get {
                return ResourceManager.GetString("tab_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1 {
            get {
                return ResourceManager.GetString("tab_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goal) Skill Cooldown(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Goal_Skill_Cooldown {
            get {
                return ResourceManager.GetString("tab_1_Goal_Skill_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bag) My cooldown recovery rate (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_My_cooldown_recovery_rate {
            get {
                return ResourceManager.GetString("tab_1_My_cooldown_recovery_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required Cooldown (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Required_Cooldown {
            get {
                return ResourceManager.GetString("tab_1_Required_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result) Skill cooldown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Result_Skill_Cooldown {
            get {
                return ResourceManager.GetString("tab_1_Result_Skill_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill cooldown (s) to calculate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Skill_cooldown_calculate {
            get {
                return ResourceManager.GetString("tab_1_Skill_cooldown_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown Required과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Whether_cooldown {
            get {
                return ResourceManager.GetString("tab_1_Whether_cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_2 {
            get {
                return ResourceManager.GetString("tab_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightning Shadow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3 {
            get {
                return ResourceManager.GetString("tab_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frostfire Rampage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4 {
            get {
                return ResourceManager.GetString("tab_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order/Chaos Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5 {
            get {
                return ResourceManager.GetString("tab_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activation Medium Skill과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6 {
            get {
                return ResourceManager.GetString("tab_6", resourceCulture);
            }
        }
    }
}
