//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tli_Utils {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tli_Utils.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You take all responsibility.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string All_responsibility {
            get {
                return ResourceManager.GetString("All_responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activation Medium Skill과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcActivationMediumSkill {
            get {
                return ResourceManager.GetString("calcActivationMediumSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcCool {
            get {
                return ResourceManager.GetString("calcCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcDMG {
            get {
                return ResourceManager.GetString("calcDMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcFreeze {
            get {
                return ResourceManager.GetString("calcFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order/Chaos Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcNewGod {
            get {
                return ResourceManager.GetString("calcNewGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   셀레나-특성 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string calcSelena {
            get {
                return ResourceManager.GetString("calcSelena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculating Armor Reduction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Calculating_Armor_Reduction {
            get {
                return ResourceManager.GetString("Calculating Armor Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frostfire Rampage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FrostRampage {
            get {
                return ResourceManager.GetString("FrostRampage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The latest version status.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Latest_version_status {
            get {
                return ResourceManager.GetString("Latest_version_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightning Shadow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lightning_Shadow {
            get {
                return ResourceManager.GetString("Lightning Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MP봉인 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MPSeal {
            get {
                return ResourceManager.GetString("MPSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chzzk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strCzz {
            get {
                return ResourceManager.GetString("strCzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Github과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strGithub {
            get {
                return ResourceManager.GetString("strGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go Main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strGoMain {
            get {
                return ResourceManager.GetString("strGoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Youtube과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string strYoutube {
            get {
                return ResourceManager.GetString("strYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guides과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_0 {
            get {
                return ResourceManager.GetString("tab_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1 {
            get {
                return ResourceManager.GetString("tab_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goal) Skill Cooldown(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Goal_Skill_Cooldown {
            get {
                return ResourceManager.GetString("tab_1_Goal_Skill_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bag) My cooldown recovery rate (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_My_cooldown_recovery_rate {
            get {
                return ResourceManager.GetString("tab_1_My_cooldown_recovery_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required Cooldown (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Required_Cooldown {
            get {
                return ResourceManager.GetString("tab_1_Required_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result) Skill cooldown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Result_Skill_Cooldown {
            get {
                return ResourceManager.GetString("tab_1_Result_Skill_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill cooldown (s) to calculate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Skill_cooldown_calculate {
            get {
                return ResourceManager.GetString("tab_1_Skill_cooldown_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooldown Required과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_1_Whether_cooldown {
            get {
                return ResourceManager.GetString("tab_1_Whether_cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예정)MP봉인 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_10 {
            get {
                return ResourceManager.GetString("tab_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지속시간 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_11 {
            get {
                return ResourceManager.GetString("tab_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_2 {
            get {
                return ResourceManager.GetString("tab_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final freeze duration (s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_2_Final_freeze_duration {
            get {
                return ResourceManager.GetString("tab_2_Final_freeze_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze default duration (s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_2_Freeze_default_duration {
            get {
                return ResourceManager.GetString("tab_2_Freeze_default_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gain Arctic when freezing. Up to 20과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_2_Gain_Extreme_when_freezing {
            get {
                return ResourceManager.GetString("tab_2_Gain_Extreme_when_freezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owned freeze duration (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_2_Owned_freeze_duration {
            get {
                return ResourceManager.GetString("tab_2_Owned_freeze_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightning Shadow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3 {
            get {
                return ResourceManager.GetString("tab_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bag) Attack/Cast Speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_bag_attack_cast_speed {
            get {
                return ResourceManager.GetString("tab_3_bag_attack_cast_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance traveled in 1 second (M)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Distance_traveled_in_1_second {
            get {
                return ResourceManager.GetString("tab_3_Distance_traveled_in_1_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Estimated number of triggers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Estimated_number_of_triggers {
            get {
                return ResourceManager.GetString("tab_3_Estimated_number_of_triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Feline Figure] Cooldown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_ff_Cooldown {
            get {
                return ResourceManager.GetString("tab_3_ff_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Feline Figure] Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_ff_Count {
            get {
                return ResourceManager.GetString("tab_3_ff_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Feline Figure] Trigger Chance (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_ff_trigger_chance {
            get {
                return ResourceManager.GetString("tab_3_ff_trigger_chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum number of [Feline Figure] activations in 4 seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Maximum_number_of_ff_activations_in_4_seconds {
            get {
                return ResourceManager.GetString("tab_3_Maximum_number_of_ff_activations_in_4_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My movement speed (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_My_movement_speed {
            get {
                return ResourceManager.GetString("tab_3_My_movement_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time taken to move 1M (s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Time_taken_to_move_1M {
            get {
                return ResourceManager.GetString("tab_3_Time_taken_to_move_1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total number of attacks in 4 seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Total_number_of_attacks_in_4_seconds {
            get {
                return ResourceManager.GetString("tab_3_Total_number_of_attacks_in_4_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total number of [Feline Figure] [shock counts] in 4 seconds
        ///(Number of Static Meteor Shock Counts)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Total_number_of_ff__shock_counts__in_4_seconds_Number_of_Static_Meteor_Shock_Counts_ {
            get {
                return ResourceManager.GetString("tab_3_Total_number_of_ff_[shock_counts]_in_4_seconds(Number_of_Static_Meteor_Shoc" +
                        "k_Counts)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Talent [Lightning Fast].과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_3_Use_Talent_Lightning_Fast {
            get {
                return ResourceManager.GetString("tab_3_Use_Talent_Lightning_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frostfire Rampage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4 {
            get {
                return ResourceManager.GetString("tab_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applied cooldown (s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_confirm_cool {
            get {
                return ResourceManager.GetString("tab_4_confirm_cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The cooldown(s) applied.
        ///In addition, the cooldown / skill effect duration is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_explain {
            get {
                return ResourceManager.GetString("tab_4_explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill effect duration is long enough.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_explain_ok {
            get {
                return ResourceManager.GetString("tab_4_explain_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frostfire Rampage, base cooldown 10 seconds, duration 5 seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_Frostfire_Rampage_exp {
            get {
                return ResourceManager.GetString("tab_4_Frostfire_Rampage_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Cooldown Recovery Rate (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_My_Cooldown_Recovery_Rate {
            get {
                return ResourceManager.GetString("tab_4_My_Cooldown_Recovery_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Skill Effect Duration (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_My_Skill_Effect_Duration {
            get {
                return ResourceManager.GetString("tab_4_My_Skill_Effect_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_4_Result {
            get {
                return ResourceManager.GetString("tab_4_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order/Chaos Calc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5 {
            get {
                return ResourceManager.GetString("tab_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At 100 points of slab, effectiveness %.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_At_points_for_each_slab {
            get {
                return ResourceManager.GetString("tab_5_At_points_for_each_slab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Example과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_example {
            get {
                return ResourceManager.GetString("tab_5_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numbers 1,4 are affected by 2 and have an effect of 20%.
        ///2,3 are influenced by 3, so the effect is 30%.
        ///Please do your own sums as the effectiveness
        ///% is different for each location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_explain {
            get {
                return ResourceManager.GetString("tab_5_explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_mini_calc {
            get {
                return ResourceManager.GetString("tab_5_mini_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of neighboring slabs (10% effect)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_Number_of_neighboring_slabs {
            get {
                return ResourceManager.GetString("tab_5_Number_of_neighboring_slabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silent Realm Use (+25% Order/Chaos Effect)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_Order_Chaos_Use {
            get {
                return ResourceManager.GetString("tab_5_Order_Chaos_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other &lt;New God Effect %&gt;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_Other_God_Talent_Effect {
            get {
                return ResourceManager.GetString("tab_5_Other_God_Talent_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Percentage of &lt;option&gt; per 1 point of Order/Chaos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_Percentage_of_option_per_1_point_of_Order_Chaos {
            get {
                return ResourceManager.GetString("tab_5_Percentage_of_option_per_1_point_of_Order_Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total effect % of all slabs combined과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_5_Total_effect_of_all_slabs_combined {
            get {
                return ResourceManager.GetString("tab_5_Total_effect_of_all_slabs_combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activation Medium Skill과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6 {
            get {
                return ResourceManager.GetString("tab_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional Character Cast Speed(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Add_Character_Cast_Speed {
            get {
                return ResourceManager.GetString("tab_6_Add_Character_Cast_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculating Wind Rhythm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Calculating_Wind_Rhythm {
            get {
                return ResourceManager.GetString("tab_6_Calculating_Wind_Rhythm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Cast Speed(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Character_Cast_Speed {
            get {
                return ResourceManager.GetString("tab_6_Character_Cast_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Cooldown Recovery Rate(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Character_Cooldown_Recovery_Rate {
            get {
                return ResourceManager.GetString("tab_6_Character_Cooldown_Recovery_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combined Wind Rhythm Cast Speed(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Combined_Wind_Rhythm_Cast_Speed {
            get {
                return ResourceManager.GetString("tab_6_Combined_Wind_Rhythm_Cast_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final Trigger Cooldown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Final_Trigger_Cooldown {
            get {
                return ResourceManager.GetString("tab_6_Final_Trigger_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit: 30 attacks/casts per second과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_limit_value {
            get {
                return ResourceManager.GetString("tab_6_limit_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of casts per second과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Number_of_casts_per_second {
            get {
                return ResourceManager.GetString("tab_6_Number_of_casts_per_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wind Rhythm Cooldown(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_6_Wind_Rhythm_Cooldown {
            get {
                return ResourceManager.GetString("tab_6_Wind_Rhythm_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculating Armor Reduction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7 {
            get {
                return ResourceManager.GetString("tab_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max 500 billion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_500b {
            get {
                return ResourceManager.GetString("tab_7_500b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   500 million과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_500m {
            get {
                return ResourceManager.GetString("tab_7_500m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50 billion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_50b {
            get {
                return ResourceManager.GetString("tab_7_50b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50 million과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_50m {
            get {
                return ResourceManager.GetString("tab_7_50m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 billion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_5b {
            get {
                return ResourceManager.GetString("tab_7_5b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enemy) Elemental Damage Reduction Rate by Resistance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Enemy__Elemental_Damage_Reduction_Rate_by_Resistance {
            get {
                return ResourceManager.GetString("tab_7_Enemy)_Elemental_Damage_Reduction_Rate_by_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enemy) Non-Physical Damage Reduction Rate by Armor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Enemy__Non_Physical_Damage_Reduction_Rate_by_Armor {
            get {
                return ResourceManager.GetString("tab_7_Enemy)_Non-Physical_Damage_Reduction_Rate_by_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enemy) Physical Damage Reduction Rate by Armor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Enemy__Physical_Damage_Reduction_Rate_by_Armor {
            get {
                return ResourceManager.GetString("tab_7_Enemy)_Physical_Damage_Reduction_Rate_by_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected) Final Damage (Physical/Non-Phy)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Expected__Final_Damage {
            get {
                return ResourceManager.GetString("tab_7_Expected)_Final_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enemy Level Input Changes Monster Armor Value. // Monster Max Level 90과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_explain1 {
            get {
                return ResourceManager.GetString("tab_7_explain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter &quot;Expected Value&quot; for User Base Damage. Unit is 1,000 (Thousands)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_explain2 {
            get {
                return ResourceManager.GetString("tab_7_explain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final) Monster Elemental Damage Multiplier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Final__Monster_Elemental_Damage_Multiplier {
            get {
                return ResourceManager.GetString("tab_7_Final)_Monster_Elemental_Damage_Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final) Monster Physical Damage Multiplier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Final__Monster_Physical_Damage_Multiplier {
            get {
                return ResourceManager.GetString("tab_7_Final)_Monster_Physical_Damage_Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final Calculation Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Final_Calculation_Result {
            get {
                return ResourceManager.GetString("tab_7_Final_Calculation_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monster Armor Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Monster_Armor_Value {
            get {
                return ResourceManager.GetString("tab_7_Monster_Armor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monster Base Resistance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Monster_Base_Resistance {
            get {
                return ResourceManager.GetString("tab_7_Monster_Base_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monster Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_Monster_Level {
            get {
                return ResourceManager.GetString("tab_7_Monster_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User) Armor Non-Physical Damage Reduction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_User__Armor_Non_Physical_Damage_Reduction {
            get {
                return ResourceManager.GetString("tab_7_User)_Armor_Non-Physical_Damage_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User) Armor Physical Damage Reduction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_User__Armor_Physical_Damage_Reduction {
            get {
                return ResourceManager.GetString("tab_7_User)_Armor_Physical_Damage_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Armor Damage Penetration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_User_Armor_Damage_Penetration {
            get {
                return ResourceManager.GetString("tab_7_User_Armor_Damage_Penetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Armor Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_User_Armor_Value {
            get {
                return ResourceManager.GetString("tab_7_User_Armor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Base Damage (Thousands)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_User_Base_Damage {
            get {
                return ResourceManager.GetString("tab_7_User_Base_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Resistance Penetration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_7_User_Resistance_Penetration {
            get {
                return ResourceManager.GetString("tab_7_User_Resistance_Penetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   셀레나-특성 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_8 {
            get {
                return ResourceManager.GetString("tab_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조수 효과 추가(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_8_tide_add {
            get {
                return ResourceManager.GetString("tab_8_tide_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지 추가 +10% , 4 초 지속 / 적 발 아래 조수, 6초 지속과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_8_tide_default {
            get {
                return ResourceManager.GetString("tab_8_tide_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조수 지속시간(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_8_tide_duration {
            get {
                return ResourceManager.GetString("tab_8_tide_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조수 효과(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_8_tide_inc {
            get {
                return ResourceManager.GetString("tab_8_tide_inc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지 계산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tab_9 {
            get {
                return ResourceManager.GetString("tab_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Announcements과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtAnnouncements {
            get {
                return ResourceManager.GetString("txtAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string txtVersionCheck {
            get {
                return ResourceManager.GetString("txtVersionCheck", resourceCulture);
            }
        }
    }
}
